### ISSUE TITLE
Show the breadcrumb type info in search

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#135]
For example, the first result here is under /guidelines/ and the other items are resources/articles: https://federalist-proxy.app.cloud.gov/site/gsa/plainlanguage.gov/search/?q=abstract

**Comment by hursey013** [comment]
I agree, this would help a lot since the page titles aren't always descriptive enough, but the current [jekyll_pages_api_search](https://github.com/18F/jekyll_pages_api_search/) plugin we are using doesn't allow this type of modification easily.

I think a solution we may want to consider in the future is perhaps leveraging https://search.gov/ as a replacement since it is being more actively developed and supported.

**Comment by nick-mon1** [comment]
This will be closed out when site is migrated.
