### ISSUE TITLE
Add Word and PDF downloads for guidelines

### ISSUE THREAD

**Issue by KatCatania** [GSA/plainlanguage.gov#54]
HI Nicole, Love the easy layout for the writing guidelines section. But I want to make sure we clearly identify them as the Federal Plain Language Guidelines. Not just Writing Guidelines. And that we have link to the full guidelines somwhere in this section. 

Also, under Plain Language Guidance and Manuals, we need to fix the blurb that talks about our guidelines like they aren't ours. 
Current blurb:
In the mid-1990s, the federal inter-agency plain language group developed a manual called Federal Plain Language Guidelines. This updated version remains a great basic manual for those of you who want to develop your plain language skills.

Suggested blurb
PLAIN's Federal Plain Language Guidelines are the best place to start. These are the official guidelines for the Plain Writing Act of 2010 and explain the basics for improving your communications skills.

**Comment by nicoleslaw** [comment]
@KatCatania I updated the blurb and the title. Two questions for you:

- Do you think `Writing guidelines` is okay for the navigation label, or would `Federal guidelines` be better?

- When you say the full guidelines, do you mean the PDF / Word doc? I want to make sure we have the latest file from you—not sure if it's changed since the live site was updated last.

**Comment by nicoleslaw** [comment]
We talked about adding this either inline under `/guidelines/index.md` or on the side of the page under the entire `guidelines` section with a more visual style.

**Comment by hursey013** [comment]
Added Word doc file in addition to the PDF.
