### ISSUE TITLE
Add `Contact us` column to footer

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#8]
- Contact us: `/contact/` (we should probably still have a form?)
- Join the listserv: https://www.digitalgov.gov/communities/plain-language-community-of-practice/
- Twitter: https://twitter.com/govplainlang
- Facebook: https://www.facebook.com/plainlanguagegov-174397429237337/

**Comment by hursey013** [comment]
@nicoleslaw I added a contact us column to the footer with the social links and email address: https://github.com/GSA/plainlanguage.gov/pull/11

Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/plainlanguage.gov/bh-update-footer/

We are limited to using Google Forms form contact forms on static sites, so unless we go that route I'm not sure if we need a `/contact/` page because they really only have an email address. Do you think we could get by with just that?

**Comment by nicoleslaw** [comment]
Sounds good to me. I'm not sure if they'll want a more formal form like @jz was showing us.

Do you think the listserv link will fit there too, or should we make it more of a button on the homepage or something?

**Comment by hursey013** [comment]
Yeah, good call, I will try adding the linkserv or finding another way to highlight it.

**Comment by hursey013** [comment]
@nicoleslaw you happy with the way this looks for now?

**Comment by nicoleslaw** [comment]
Looks good to me!
