### ISSUE TITLE
Style agency contacts page

### ISSUE THREAD

**Issue by hursey013** [GSA/plainlanguage.gov#82]
Right now it's just a long list, perhaps use some anchor links or another way to condense the list a bit. https://federalist-proxy.app.cloud.gov/site/gsa/plainlanguage.gov/law/requirements/agency-contacts/

**Comment by nicoleslaw** [comment]
I am working on cleaning [this page up on a branch](https://federalist-proxy.app.cloud.gov/site/gsa/plainlanguage.gov/resources/guides/), but I am wondering if we should move the links to agency style guides to this page instead of having them on an island in /resources/. I could go either way...

Just making a note in case you have an opinion (and I am assuming it would affect the yml file structure a bit).

**Comment by nicoleslaw** [comment]
User quote:

> "Agency contact - have the department wide info listed first, and then if there is a secretary or something have that second."

**Comment by nicoleslaw** [comment]
One more!:

> Agency contacts - I find these pages difficult because you have to scroll and scroll. Maybe you can make these details collapsable, I hate scrolling, pet peeve. Or some of them have A | B | C, etc so it can jump you down to the area you want.

**Comment by hursey013** [comment]
I reworked the contacts data file to include some additional details I didn't originally capture. I also added a bunch of checks to the Agency Contacts page to conditionally display department wide info, senior official, and contacts depending on what is actually available. 

https://federalist-proxy.app.cloud.gov/site/gsa/plainlanguage.gov/law/agency-contacts/

https://github.com/GSA/plainlanguage.gov/commit/145b5aaef443c15328bf49fbeb4438b0fc2ac9be
